title: Nomisma.org
email: egruber@numismatics.org
description: >- # this means to ignore newlines until "baseurl:"
  Nomisma.org is a collaborative project to provide stable digital representations of numismatic concepts according to the principles of Linked Open Data.
baseurl: "/nomisma" # the subpath of your site, e.g. /blog
url: "http://nomisma.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ewg118
github_username:  ewg118

# Build settings
theme: minima
plugins:
  - jekyll-feed
  
collections:
    scientific_committee:
        output: true
        sort_by: id

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
